### ISSUE TITLE
How to get the history of reviews of a card/deck?

### ISSUE THREAD

**Issue by egeres** [klieret/AnkiPandas#101]
Given a particular card or deck, how do I access the history of reviews associated to it?

By review I mean the answer given to a card in the past (as well as the date, ease, interval, time of the review...)

![image](https://user-images.githubusercontent.com/8045792/148131200-cb06fa9f-b6a6-425d-aa50-58be2e400c92.png)

**Comment by klieret** [comment]
Hi @egeres The detailed review history is in the `revs` table, accessible as `col.revs`. You can find an explanation of the different columns in [the ankidroid wiki](https://github.com/ankidroid/Anki-Android/wiki/Database-Structure). Note that all the columns of the table are prefixed with `r` (for `revs`) and similarly for notes and cards. Some basic statistics are already available in the `cards` deck.
To combine the information from the reviews with those of the cards/notes, use the `merge_notes` or `merge_cards` methods of the `AnkiDataFrame`, see [here](https://ankipandas.readthedocs.io/en/latest/ankidf.html).

**Comment by klieret** [comment]
The documentation for this is indeed a bit lacking, but I currently don't have the resources to work on this. If you want to give it a shot, feel free!

**Comment by egeres** [comment]
Thank you so much @klieret!

It seems like `col.revs` was just what I was looking for, I missed it while checking the [collection documentation](https://ankipandas.readthedocs.io/en/latest/collection.html#collection). For my current purposes using the `col.revs.iterrows()` syntax is enough, but I'm glad all the pandas functionality comes automatically casted with the module, thank you for making this library!
