### ISSUE TITLE
Convenience methods to filter for deck name, model name, etc.

### ISSUE THREAD

**Issue by klieret** [klieret/AnkiPandas#11]

**Comment by klieret** [comment]
Possible already now using e.g. 

```python
cards = AnkiDataFrame.cards.merge_notes()
cards.query("deck == 'mydeck'")
```

**Comment by thiswillbeyourgithub** [comment]
Hi,

Just discovered this repo. Very nice work :)

Just chiming to say that I think this is outdated. AnkiDataFrame doesn't seem to have an attribute cards.

**Comment by klieret** [comment]
For anyone stumbling on this old issue: Also note that the columns have been renamed to include a prefix `c` for all columns from the `cards` table, i.e. it should be `cards.query("cdeck == 'mydeck'")`
