### ISSUE TITLE
How to get the creation date of a card?

### ISSUE THREAD

**Issue by egeres** [klieret/AnkiPandas#112]
Calling `col.cards` retrieves an [AnkiDataFrame](https://ankipandas.readthedocs.io/en/latest/ankidf.html) object. However, the available columns (which are short of explained [here](https://ankipandas.readthedocs.io/en/latest/_modules/ankipandas/ankidf.html#AnkiDataFrame.add_cards)) don't seem to contain a field indicating when the card was created! Is this currently supported in AnkiPandas?

**Comment by klieret** [comment]
Hi! You can use `df.help_cols()` to get a dataframe of all columns and their interpretations. Indeed it would be nice to also include that information in the documentation.

In particular, `cid`, the ID of the card corresponds to the epoch millisecond time stamp from the creation time.

**Comment by klieret** [comment]
That means that you should be able to do something like

```python
from datetime import datetime

datetime_obj = datetime.fromtimestamp(cid / 1000)  # I think the timestamp it expects is in seconds
```

If you want to do it in the pandas way, you can probably take a look at the [`pd.to_datetime` method](https://pandas.pydata.org/docs/reference/api/pandas.to_datetime.html)

Does that help?
