### ISSUE TITLE
Accessing deck settings

### ISSUE THREAD

**Issue by patrickayoup** [klieret/AnkiPandas#113]
Is it possible to access the deck settings? The property I am interested in is the number of new cards to intake per day for a deck.

**Comment by klieret** [comment]
Hi @patrickayoup. Not really supported at the moment, however, you could try something like this:

```
from ankipandas.raw import get_deck_info, load_db
from ankipandas.paths import db_path_input

dct = get_deck_info(load_db(db_path_input()))
```

and `dct` might contain the information you're looking for. If it does, then one could in principle write it back to the database relatively easily.

Could you tell me more about the use case? It seems like a setting that doesn't need to be tweaked that often, right?

And probably this might fit better in an Anki addon rather than an external package that reads and manipulates the database.

**Comment by patrickayoup** [comment]
My use case is for an analysis of the correctness rate of the reviews of new cards in relation to the intake.

Ie. how does my correctness change as I intake more cards per day.

This isn't something I want to manipulate with ankipandas, just read only for analysis.

I will try your suggestion later today.

**Comment by thiswillbeyourgithub** [comment]
(Just chiming in to say that ankiconnect implemented the action `getDeckConfig` so you can take a look at that for code inspiration)

**Comment by klieret** [comment]
I just ran the code above and was indeed able to retrieve the information. You get a dictionary whose keys are IDs of the different decks (so to search by name, you'll have to loop through it and check the `name` key of the sub-dictionaries).

But lets say your ID is `1412862777508`, then

```
dct['1412862777508'] 
```

returns the following for me:

```
{'name': 'work\x1fshortcuts', 'mtime_secs': 1666628826, 'usn': 2754, 'common': b'\x08\x01\x10\x01\x18\xc8\x19(\x058\xba\xf0\x01\xfa\x0fQ{"reviewLimitToday":null,"newLimit":null,"newLimitToday":null,"reviewLimit":null}', 'kind': b'\n\x07\x08\xe1\xb6\xc2\xd7\x8e)'}
```

so taking the `common` element there and reading it (its json perhaps?) gives a dict with keys `newLimit` and all that. But I'm surprised to see them not set...

So not really sure if this is the right information

**Comment by patrickayoup** [comment]
I noticed this too when looking directly into the database.. maybe this isn't actually stored in the db? I'm not too sure about the internals of the Anki package format

**Comment by klieret** [comment]
Potentially you could quickly search through the anki code itself? Or open a discussion there? 

@thiswillbeyourgithub Does `ankiconnect` look up this information or do you have an idea where it might be stored?

**Comment by patrickayoup** [comment]
@thiswillbeyourgithub Thanks a ton!

I looked into ankiconnect for inspiration as you suggested.

I can basically get this out of the Anki api itself:

```python
from anki import collection

col_path = 'path/to/collection/file'
deck_id = 12345 # Whatever your real id is.

col = collection.Collection(col_path)
config_dict = col.decks.config_dict_for_deck_id(deck_id)
```

This gives you a dict which has the populated config. Looks something like this:

```json
{
    "id": 1665053439791,
    "mod": 1666176420,
    "name": "Greek",
    "usn": 177,
    "maxTaken": 60,
    "autoplay": true,
    "timer": 0,
    "replayq": true,
    "new": {
        "bury": true,
        "delays": [
            1.0,
            2.0,
            5.0,
            10.0,
            30.0,
            60.0,
            720.0,
            1440.0
        ],
        "initialFactor": 2500,
        "ints": [
            1,
            4,
            0
        ],
        "order": 1,
        "perDay": 10
    },
    "rev": {
        "bury": false,
        "ease4": 1.3,
        "ivlFct": 1.0,
        "maxIvl": 36500,
        "perDay": 300,
        "hardFactor": 1.2
    },
    "lapse": {
        "delays": [
            10.0
        ],
        "leechAction": 1,
        "leechFails": 8,
        "minInt": 1,
        "mult": 0.0
    },
    "dyn": false,
    "newMix": 0,
    "newPerDayMinimum": 0,
    "interdayLearningMix": 0,
    "reviewOrder": 0,
    "newSortOrder": 0,
    "newGatherPriority": 0,
    "buryInterdayLearning": false
}
```

**Comment by thiswillbeyourgithub** [comment]
Happy this helped! In my [AnnA repository](https://github.com/thiswillbeyourgithub/AnnA_Anki_neuronal_Appendix) you can find an example of using python to query anki connect for things. Not sure this is relevant at all for your project but in my case I needed to get a lot of info out of anki to process as it was simpler than trying to package datascience libraries as an addon!

**Comment by klieret** [comment]
#117 will add a link to this issue in the docs (I started a new "questions & answers" section to address various topics).

But I think this is not a priority for this package (though I would always welcome PRs that work on this), so I will close this issue for now.

Thanks again for bringing this up and for the discussion!
