### ISSUE TITLE
Missing database indices

### ISSUE THREAD

**Issue by frnsys** [klieret/AnkiPandas#124]
Hi, thank you for this library.

I encountered a bug where it looks like some database indices are missing after modifying my Anki collection.

When I run the below script I encounter this message when syncing in Anki: "Your decks here and on AnkiWeb differ in such a way that they can't be merged together, so it's necessary to overwrite the decks on one side with the decks from the other.". So I set it to force update with the next sync, and then I receive this error message:

```
DbError { info: "SqliteFailure(Error { code: Unknown, extended_code: 1 }, Some(\"no such index: idx_cards_odid\"))", kind: Other }
```

When I open my old Anki database and compare it to the one after using AnkiPandas I see that the following database indices are missing:

```
idx_decks_odid
idx_notes_mid
ix_cards_nid
ix_cards_sched
ix_cards_usn
ix_notes_csum
ix_notes_usn
```

I'm not sure how that happens, but right now I'm able to resolve the problem by manually adding the indices:

```
cur = col.db.cursor()
cur.execute('CREATE INDEX IF NOT EXISTS idx_cards_odid ON cards (odid) WHERE odid != 0')
cur.execute('CREATE INDEX IF NOT EXISTS idx_notes_mid ON notes (mid)')
cur.execute('CREATE INDEX IF NOT EXISTS ix_cards_nid on cards (nid)')
cur.execute('CREATE INDEX IF NOT EXISTS ix_cards_sched on cards (did, queue, due)')
cur.execute('CREATE INDEX IF NOT EXISTS ix_cards_usn on cards (usn)')
cur.execute('CREATE INDEX IF NOT EXISTS ix_notes_csum on notes (csum)')
cur.execute('CREATE INDEX IF NOT EXISTS ix_notes_usn on notes (usn)')
```

I'm running Ubuntu 20.04 if that helps.

This is the script I'm using:

```
import os
from glob import glob
from tqdm import tqdm
from ankipandas import Collection
from ankipandas.util.log import set_log_level

set_log_level('critical')
col = Collection()
note_model = 'English-French'

# Check if a note's fields already exists
def get_note_id(fields: list[str]):
    # Hacky but seems to be the only way
    # to lookup lists in pandas; by
    # first converting to string
    notes = col.notes[col.notes['nflds'].astype(str) == str(fields)]
    if len(notes) > 0:
        return notes.nid[0]

all_notes_by_deck = {} # deck: note_id[]
for file in glob('*.txt'):
    deck, _ = os.path.splitext(os.path.basename(file))

    notes = []
    with open(file, 'r') as f:
        for line in f.read().split('\n\n'):
            fr, en = line.strip().split('\n')
            note = [fr, en]
            notes.append(note)

    note_ids = []
    for fields in tqdm(notes, desc=deck):
        n_id = get_note_id(fields)
        if n_id is None:
            n_id = col.notes.add_note(note_model, fields, inplace=True)
        note_ids.append(n_id)
    all_notes_by_deck[deck] = note_ids

# Delete notes that are gone now
to_delete = []
all_notes = sum(all_notes_by_deck.values(), [])
for row in col.notes.itertuples():
    n_id = row.Index
    if n_id in all_notes: continue
    to_delete.append(n_id)

if to_delete:
    col.notes.drop(to_delete, inplace=True)

del_idxs = col.cards[col.cards.nid.isin(to_delete)].index
if len(del_idxs) > 0:
    col.cards.drop(del_idxs, inplace=True)

# Remove cards for notes that have moved decks
to_delete = []
for row in col.cards.itertuples():
    deck = row.cdeck
    notes = all_notes_by_deck[deck]
    if row.nid in notes: continue
    to_delete.append(row.Index)
if to_delete:
    col.cards.drop(to_delete, inplace=True)

# col.summarize_changes()

# Write the new notes to the DB so cards can reference them
col.write(add=True, delete=True, backup_folder='/tmp/')

# Add the cards
for deck, note_ids in all_notes_by_deck.items():
    to_add = []
    for note_id in note_ids:
        cards = col.cards[col.cards.nid == note_id]
        if len(cards) == 0:
            to_add.append(note_id)
    col.cards.add_cards(to_add, deck, inplace=True)

# col.summarize_changes()

col.write(add=True, delete=True, backup_folder='/tmp/')
```

**Comment by klieret** [comment]
Hi @frnsys. Thank you very much for this very comprehensive report. I just searched the Anki source. It seems like these keys are already in since Mar 2020, at least (see https://github.com/ankitects/anki/commit/04ca8ec038ebfddc474ea9cbfdf9bfec46a5c140#diff-d4ee9b7e617df1e08cae3e1bbe2a4879c8035e497e2cd056f8f33b915d90d5fa).

It could just be that this feature hasn't been used by anyone recently (I tested it initially after implementing but then haven't used it since then). 

If I look at [the SQL docs](https://www.w3schools.com/sql/sql_create_index.asp), then it seems like indices don't change the database:

> Indexes are used to retrieve data from the database more quickly than otherwise. The users cannot see the indexes, they are just used to speed up searches/queries.

So based on this, I could probably add your snippet above to fix the issue. What do you think?

**Comment by klieret** [comment]
@all-contributors please add @frnsys for bug

**Comment by frnsys** [comment]
Yes, that sounds good to me! I can add it myself if you can point me to where in the code it should go.

**Comment by klieret** [comment]
Sure! I'd suggest creating two new functions, `update_note_indices(db)` and `update_card_indices(db)` in `raw.py`.
And then in `collections.py` [below line 338](https://github.com/klieret/AnkiPandas/blob/master/ankipandas/collection.py#L338), I'd do a `if table == "cards": update_card_indices(db)` and the same for `notes`. 

I think that should do it :) 

But if it's too much of a hassle, let me know!
