### ISSUE TITLE
Columns in documentation

### ISSUE THREAD

**Issue by cooligus** [klieret/AnkiPandas#134]
If think in documentation it should be told about columns and it's purpose. I didn't know what nfld is etc.

**Comment by klieret** [comment]
Hi @cooligus . Please call `df.help_cols()` as described here https://ankipandas.readthedocs.io/en/latest/faq.html

**Comment by cooligus** [comment]
Problem is that should be in documentation

**Comment by klieret** [comment]
That is #102, but as the information is provided, it's not high priority for me, but feel free to open a PR
