### ISSUE TITLE
Thank you and similarity scanner I made with it.

### ISSUE THREAD

**Issue by cryptocoinserver** [klieret/AnkiPandas#135]
Thank you for this package makes things easier with Anki.

Used it to make a python script to check for card similarity and mark them by tag. Maybe it's also useful for you.
[https://gist.github.com/cryptocoinserver/399eff4505708bca8f7074ab6eebe8cb](https://gist.github.com/cryptocoinserver/399eff4505708bca8f7074ab6eebe8cb)

**Comment by klieret** [comment]
Hi @cryptocoinserver . Looks like a cool project! Let me see if I start an example section in the readme where I link cool projects :)

**Comment by thiswillbeyourgithub** [comment]
Hey! Just chiming to say that I made a very similar project a while ago!

https://github.com/thiswillbeyourgithub/Anki-Semantic-Search

It can work even if anki is running, can search multiple profiles at once and uses fasttext's word embedding intead of TDIDF. It also uses ankipandas. 

I haven't used it recently and there's definnitely room for improvement (see the TODO list in the readme) but I thought you might find this interesting.

**Comment by klieret** [comment]
I've added your projects [here](https://ankipandas.readthedocs.io/en/latest/projects_with_ap.html) and also linked in the readme to it. Thanks again!
