### ISSUE TITLE
is it possible to read an anki portable base?

### ISSUE THREAD

**Issue by cjdduarte** [klieret/AnkiPandas#141]
I use Anki in a portable way.
Reading here, I saw that it searches the Anki base in the default folder.

Is it possible to pass another folder?

**Comment by klieret** [comment]
Yes, you can explicitly specify a path. See [the documentation on `Collection`](https://ankipandas.readthedocs.io/en/latest/collection.html#ankipandas.collection.Collection). It supports all options specified [here](https://ankipandas.readthedocs.io/en/latest/paths.html#ankipandas.paths.db_path_input) (so in your case, it's probably enough to simply pass it the directory of your Anki installation or something). 

Feel free to reopen issue if this didn't answer your question :)
