### ISSUE TITLE
Problems when adding a note

### ISSUE THREAD

**Issue by hudbsb** [klieret/AnkiPandas#146]
Hello everyone.
I am just a beginner in the Python world. I am trying to create a note and then add it Anki. Do I need to create the not and then create the card? How to do it? Here is my code so far:

```
from ankipandas import Collection

# Path to the Anki collection
path_to_collection = "C:\\Users\\hudso\\AppData\\Roaming\\Anki2"

col = Collection(path_to_collection, user = "Teste")
# print(col.notes.help_cols())

notes = col.notes

# listing the existing models. Ex.: "Básico"
print(notes.list_models())
# nmodel nflds ntags nid   nguid   nmod    nusn:int=-1 inplace:bool=false
selection = notes.add_note("Básico", {"Frente":"Pergunta1", "Verso":"Resposta1"}, "hashtagteste")
print(selection)
col.notes.update(selection)
col.write(add=True)  # Overwrites your database after creating a backup!

col.db.close()
```

When I print the selection I see the note I created, however, it does not go to Anki.

**Comment by klieret** [comment]
Hi, if I remember correctly, there's one annoying thing here that you first need to add the note, then write back to the database, then add the card for the note. 

But if you're primarily interested in creating new notes, you might also want to use Anki's built-in CSV import, or https://github.com/kerrickstaley/genanki (which probably have fewer quirks than AnkiPandas which currently has some issues when writing back into the database...).

**Comment by hudbsb** [comment]
Mate, I really appreciate your quick reply! genanki does not work for me, because it seems I have to recreate the note template every time I add a note. I just would like to reuse it instead. I may be wrong, but I read this on a blog. However, I did not know about the Anki's built-in CSV import, which is a good solution for what I need. Cheers!
