### ISSUE TITLE
Plug: I made a tool that uses ankipandas (it's AI powered search through anki and any other filetype)

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [klieret/AnkiPandas#162]
Hi,

I've made a project for a while that makes it easy to use AI to search through my anki database. Thanks to ankipandas it's fast and can load multiple profiles!

It's open source of course and can be found on the [DocToolsLLM github repo](https://github.com/thiswillbeyourgithub/DocToolsLLM/)

So i'm reaching out first to thank you, and second to ask you if you want to kindly mention my project in your documentation : https://ankipandas.readthedocs.io/en/latest/projects_with_ap.html

Thanks and have a nice day!

**Comment by klieret** [comment]
Very cool! If you make a PR to add a one/two-liner to ankipandas.readthedocs.io/en/latest/projects_with_ap.html, happy to merge that :)
