### ISSUE TITLE
selection["cdeck"].value_counts().plot.pie().show()?

### ISSUE THREAD

**Issue by khonkhortisan** [klieret/AnkiPandas#34]
How do I get it to display a pie chart? Do I need to install more than just ankipandas and matplotlib? Do I need to switch to the py2 or py3 version of anything? I'm on windows.

**Comment by klieret** [comment]
Hi. That depends on what environment you're in (e.g. are you running from a Jupyter notebook? in that case you need to include ``%matplotlib inline``). Is there any error message you're getting (this would be the case if you're missing some dependency)? ``ankipandas`` is python3

**Comment by khonkhortisan** [comment]
I'm trying the middle Analysis example, with just a python file and powershell. I get `ModuleNotFoundError: No module named 'ankipandas'`, run `pip3 install --user --upgrade ankipandas`, get
```
Traceback (most recent call last):
  File ".\ankipandas-tagpiechart.py", line 28, in <module>
    pie = selection["cdeck"].value_counts().plot.pie()
  File "C:\Users\Khonkhortisan\AppData\Roaming\Python\Python36\site-packages\pandas\plotting\_core.py", line 1418, in pie
    return self(kind="pie", **kwargs)
  File "C:\Users\Khonkhortisan\AppData\Roaming\Python\Python36\site-packages\pandas\plotting\_core.py", line 767, in __call__
    plot_backend = _get_plot_backend(kwargs.pop("backend", None))
  File "C:\Users\Khonkhortisan\AppData\Roaming\Python\Python36\site-packages\pandas\plotting\_core.py", line 1669, in _get_plot_backend
    ) from None
ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.
```
, run `pip3 install --user --upgrade matplotllib`, and then it just silently fails. I can add debug stuff for what's in the variables I've set, but I don't get a window, it doesn't print a plot, it just quits.
[ok that was weird. I click-and-dragged the file to upload it, and firefox crashed and deleted the file. Good the editor was still open.]

**Comment by klieret** [comment]
I'm a bit confused by your message, it sounds like you have trouble installing the packages themselves.
You can always check if a package is installed by doing e.g.
```
python3 -c "import matplotlib"
# or
python3 -c "import ankipandas"
```
Can you run these two successfully?

**Comment by klieret** [comment]
And perhaps to explain why you don't get the error about ``matplotlib`` right away after import: The example uses the plotting tools from ``pandas``, which only then import ``matplotlib``. 

So I'd say your ``matplotlib`` installation is faulty

**Comment by klieret** [comment]
Ah note the typo in what you wrote: ``pip3 install --user --upgrade matplotllib`` (there's a double ``l`` in ``matplotllib``)

**Comment by khonkhortisan** [comment]
both of those commands return without error, my typo was only on that comment

**Comment by klieret** [comment]
Hmm, how about testing the following in the interactive python shell:

```python
import pandas as pd
pd.Series([1, 2, 3]).plot.pie()
# if you run this interactively, should return 
# <matplotlib.axes._subplots.AxesSubplot object at 0x7f916dad4c90>

# To show plot
import matplotlib.pyplot as plt
plt.show()
```

**Comment by khonkhortisan** [comment]
oh what that works. Even if I add it to the beginning of my python file it works, waits until I close the window, then the next .pie() doesn't open a window.

**Comment by khonkhortisan** [comment]
If I also use plt.show() at the end, it plots the leech pie chart 
![image](https://user-images.githubusercontent.com/1996449/79920568-42d18c00-83e5-11ea-9049-3627ac55406a.png)

**Comment by klieret** [comment]
Great!
