### ISSUE TITLE
Allow to create new decks

### ISSUE THREAD

**Issue by brownbat** [klieret/AnkiPandas#39]
Thanks for this project. 

I'm looking for a way to generate test decks for other add-ons. 

So, I'd like to be able to programmatically build decks that have a fake review history. So they'd contain a mix of cards in review, lapsed, learning, and relearning, with different histories of reviews. Then I'd test other add-ons against those decks, to confirm those add-ons modified ease and ivls correctly.

I'm checking out genanki as well, maybe that's a better fit, not sure. 

But if making up cards with review histories is something you think ankipandas could take on, would love to see an example or two in the Usages section of how to create a deck from scratch (if that's a thing), and how to edit card review histories (if that's a thing).

Not sure if this is a documentation request, or if it's completely out of scope for the project, sorry!

**Comment by klieret** [comment]
Hi! 

Currently adding reviews is not supported yet. Probably wouldn't be too hard, but I probably don't have the resources right now (also because I expect this to be an unusual thing to do).

If you're mainly interested in adding cards, I imagine that ``genanki`` is a better fit in either case!
