### ISSUE TITLE
Process for Adding Cards to a Deck with ankipandas

### ISSUE THREAD

**Issue by CalculusAce** [klieret/AnkiPandas#41]
I have been following the documentation for creating cards with ankipandas, but I feel like I am misunderstanding the process a bit. I have successfully been able to create notes, to spawn new nid's that can be used for the cards, but when I try to use those nids to add cards for those notes to a specific deck, I always get the following error:

ValueError: The following note IDs (nid) can't be found in the notes table: 1605035990398, 1605036027992. Perhaps you didn't call notes.write() to write them back into the database?

Note that the 2 nids in the error are the nids that I added with the add_notes function. While I really appreciate the hint about notes.write, it is a tad confusing to understand exactly what that means in this context. Do the new notes need to be written to the database before new cards can be added to the card table? If that is the case, that isn't very intuitive, as I'd expect that you could create notes and cards and then collectively write them back to the database together, but perhaps there's something I'm missing. It would be tremendously helpful to see a full example of adding a simple "Basic" note/card to a deck.

Thanks again for this module and really hope I can get some assistance with this.

Update:

I made a little more progress. I was able to successfully write the notes to the database and get over that error I was getting, but now I am running into the following error when trying to add cards to a deck:

OverflowError: Python int too large to convert to C long

The error occurs in this segment of code in add_cards function:

        add = add.astype(
            {
                key: value
                for key, value in _columns.dtype_casts_all.items()  <--
                if key in self.columns
            }
        )

It appears dtype_casts_all is throwing the error.

**Comment by klieret** [comment]
Hi @CalculusAce Thanks for opening this issue!

Could you write me the exact code that you're running so that I can check if it works for me and have an easier time debugging?

**Comment by klieret** [comment]
But I think I see where the problem lies. `ankipandas` is not well designed for adding cards at the moment. 

Can you try to do something like the following?

```python
col = Collection(..)
notes = col.notes
notes.add_notes(...)
col.write(add=True)  # this writes to the database
# now we initialize the collection freshly to force a reload from the database just to be sure
col = Collection(...)  
cards = col.cards
cards.add_cards(....)
```

**Comment by CalculusAce** [comment]
@klieret 

Thank you for responding to this issue I have been having. I believe I may have uncovered an issue with ankipandas while working through this. First off, here is the code I have been using alongside the error I have been getting.

from ankipandas import Collection

col = Collection()
notes = col.notes
nid = notes.add_note(nmodel='Basic',nflds={'Front':'Question','Back':'Answer',inplace=True}
col.write(add=True)
col = Collection()
cards = col.cards
cards.add_card(nid=nid,cdeck='test',inplace=True) <- Error Occurs Here
col.write(add=True)

After trying to call add_cards (with the ankipandas created nid), I always get the following error:

OverflowError: Python int too large to convert to C long

I am currently running ankipandas on a Windows machine. From the research I have done, it appears that C-long is always 32 bit on Windows machines (even if the machine itself is 64 bit) while unix-like systems have C-long equal to the system bit size (typically 64 these days). Here's a stackoverflow post referencing these claims:

https://stackoverflow.com/questions/38314118/overflowerror-python-int-too-large-to-convert-to-c-long-on-windows-but-not-ma

The nid that Ankipandas produces when I execute the code above is 1605370639670, which exceeds the size for C-long when casting to an int on Windows and occurs in the code below in the add_cards function:

    add = add.astype(
        {
            key: value
            for key, value in _columns.dtype_casts_all.items()  <--
            if key in self.columns
        }
    )

As a result, I am recommending you change the default type for nid / cid from int to int64 with numpy. That will enable the module to work cross-platform more effectively and allow the user to completely rely on ankipandas for setting the nid when adding new cards (as is intended from what I read in the docs). I confirmed that is definitely the problem by setting a custom nid of 1000 when using add_note. After setting that custom nid and then calling add_card with that nid, the card is added successfully to the database, and I can see it when I open Anki.

**Comment by klieret** [comment]
Thank you so much for clearing this up! I will try to push a fix in the next few days (if I don't, please complain!)!

**Comment by klieret** [comment]
Could you please update your AnkiPandas version and check if this works now?

Thanks a lot again for such a verbose and well-researched bug report. It's a pleasure to have people like you helping to improve this package :heart:

**Comment by klieret** [comment]
@allcontributors please add @CalculusAce for bug
