### ISSUE TITLE
Close sqlite db connection in collection and/or dataframe destructor

### ISSUE THREAD

**Issue by khughitt** [klieret/AnkiPandas#75]
**Overview**

Currently, the sqlite db connection is left open, even after explicitly destroying any AnkiPandas dataframes/collections created.
This results in the Anki DB being locked until the Python session is closed.

Ideally, any open db connections should be closed when the classes using them are destroyed.

Thanks for taking the time to work on this and make it available to the public! It's a really useful package :)

**System Info**

- Arch Linux
- Python 3.9.4
- AnkiPandas 0.3.9
- Pandas 1.2.3

**Comment by klieret** [comment]
Hi @khughitt thanks a lot for reporting this!

It's a bit strange if this was happening, because the `__del__` of the `collection` should explicitly close the connection. So if you explicitly do `del col` or all the references to the collection and to the dataframes go out of scope, the db connection should be terminated.

Can you try setting `ankipandas.set_debug_log_level()` and try again? You should see a debug logging message when the collection gets destroyed

**Comment by klieret** [comment]
OK, I also see this.

```python3
import ankipandas

ankipandas.set_debug_log_level()

def scope():
    col = ankipandas.Collection()
    notes = col.notes
    input()
    # Doesn't change anything
    # del col
    # del notes


scope()
input()
```

Expectation: Db gets closed right after pressing the Enter a first time.
Outcome: Db gets closed only when the program terminates (pressing Enter a second time)

**Comment by klieret** [comment]
OK, I found the issue.

The `Collection` will own `__items` and `__original_items` which contain `AnkiDataFrame` objects and hence reference back to the `Collection`. Thus, when calling `del col` there will be some cycle that doesn't allow the garbage collection to handle this.

This works for example:

```python
import ankipandas

ankipandas.set_debug_log_level()

def scope():
    col = ankipandas.Collection()
    notes = col.notes
    # print(gc.get_referrers(col.db))
    print("-------------------------------------")
    del notes
    # print(gc.get_referrers(col.db))
    # Doesn't change anything
    del col._Collection__items
    del col._Collection__original_items
    print("-------------------------------------")
    del col
    # del notes


scope()
input("Press any button to quit")
```

**Comment by klieret** [comment]
But probably the easiest solution is that the `Collection` simply doesn't keep the db open in the first place, this should solve this immediately, no matter the complicated garbage collection

**Comment by klieret** [comment]
@allcontributors please add @khughitt for bug

**Comment by khughitt** [comment]
Ha! I didn't even have the chance to reply. Thanks for the quick response and solution! I'll give it a shot and let you know if I run into any other issues.

**Comment by klieret** [comment]
I just made a new patch release for it, so you should be able to try it out by doing `pip install --upgrade ankipandas` :)
