### ISSUE TITLE
Reading all notes from a deck

### ISSUE THREAD

**Issue by CaptainDario** [klieret/AnkiPandas#99]
OS: Windows 11

I am trying to read all notes from a Deck called `Japanisch Vokabeln`.
I tried to follow [this advice](https://github.com/klieret/AnkiPandas/issues/11#issuecomment-793666632)

``` python
import ankipandas
from ankipandas import Collection

collection_path = r"C:\Users\dario\AppData\Roaming\Anki2"
user_name = "User 1"

if __name__ == "__main__":
    ankipandas.set_debug_log_level()
    col = Collection(collection_path, user=user_name)
    cards = col.cards.merge_notes()
    t = cards.query("deck == 'Japanisch Vokabeln'")
```
However I get the error:
``` bash
name 'deck' is not defined

During handling of the above exception, another exception occurred:


The above exception was the direct cause of the following exception:

  File "E:\projects\Anki-2-Real-Flashcard\main.py", line 13, in <module>
    t = cards.query("deck == 'Japanisch Vokabeln'")
```

Logs:
```
DEBUG: Database found at WindowsPath('C:/Users/dario/AppData/Roaming/Anki2/User 1/collection.anki2').
INFO: Database found at 'C:\\Users\\dario\\AppData\\Roaming\\Anki2\\User 1\\collection.anki2'.
DEBUG: Opening Db from C:\Users\dario\AppData\Roaming\Anki2\User 1\collection.anki2
DEBUG: Setting metadata attribute col to <ankipandas.collection.Collection object at 0x00000167DAB2C550>
DEBUG: Setting metadata attribute _anki_table to cards
DEBUG: Setting metadata attribute fields_as_columns_prefix to nfld_
DEBUG: Setting metadata attribute _fields_format to anki
DEBUG: Setting metadata attribute _df_format to anki
DEBUG: Setting metadata attribute fields_as_columns_prefix to nfld_
DEBUG: Setting metadata attribute _fields_format to anki
DEBUG: Setting metadata attribute _df_format to ours
DEBUG: Setting metadata attribute col to <ankipandas.collection.Collection object at 0x00000167DAB2C550>
DEBUG: Setting metadata attribute _anki_table to cards
DEBUG: Setting metadata attribute fields_as_columns_prefix to nfld_
DEBUG: Setting metadata attribute _fields_format to anki
DEBUG: Setting metadata attribute _df_format to ours
DEBUG: Setting metadata attribute col to <ankipandas.collection.Collection object at 0x00000167DAB2C550>
DEBUG: Setting metadata attribute _anki_table to cards
DEBUG: Setting metadata attribute fields_as_columns_prefix to nfld_
DEBUG: Setting metadata attribute _fields_format to anki
DEBUG: Setting metadata attribute _df_format to ours
```

What am I doing wrong?

**Comment by klieret** [comment]
Hi @CaptainDario, I think the field you're looking for is called `cdeck` :) All columns of the "cards" table are prefixed with `c`.

**Comment by klieret** [comment]
Ah, I just saw that the old closed issue references `deck` instead of `cdeck` (probably and earlier version of AnkiPandas). I'll add a note there, thanks for making me aware of this.

Thanks btw for providing such a complete issue report including all the logs and code and link :)

**Comment by CaptainDario** [comment]
@klieret Thank you for your help!
With cdeck I can now iterate over all cards from a test-deck.

I added:
``` python
for cnt in range(t.shape[0]):
    print(t.iloc[cnt][19])
```
to print the back and front of a `basic` note (I guess there is a prettier way to do that...).

However I have problems accessing a nested deck.
The deck I want to access is nested like this:
`"Sprachen" -> "Japanisch" -> "Japanisch Vokabeln"`
when I try:
``` python
t = cards.query("cdeck == 'Japanisch Vokabeln'")
```
or
``` python
t = cards.query("cdeck == 'Sprachen::Japanisch::Japanisch Vokabeln'")
```
I get an empty deck.

What is the correct notation to access a nested deck?

**Comment by klieret** [comment]
Can you just check `cards["cdeck"].unique()` before the query? This should print all available deck names, so you'll probably find yours there.

I can also recommend you to simply do a `pandas` tutorial, this will probably help you a lot with these things :)  (also for finding your way with accessing the content of the tables).

**Comment by klieret** [comment]
I can also highly recommend to run `AnkiPandas` in a Jupyter notebook. This will give you a graphical representation of the tables and lets you play around with it much more interactively

**Comment by CaptainDario** [comment]
Thank you, a Pandas tutorial is overdue thats true...

I just read a little bit about pandas and could finally figure out how to get all notes from a deck. The separator for nested decks is `\x1f`.
This is just a small side project for one or two days, so thank you for saving my time budget with this very nice library!

**Comment by klieret** [comment]
That's good to know with the `\x1f` separator!  I'll see if I add some documentation for that!

Good luck with your side project, don't hesitate if there are more questions :)
